name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Website
      - name: Build Website
        working-directory: newskarnataka-website
        run: npm install --legacy-peer-deps && npm run build
        env:
          NEXT_PUBLIC_STRAPI_URL: http://103.191.208.235:1337
          STRAPI_API_TOKEN_FULL_ACCESS: a18e5bcb9bc06d3af2e522ba790c6e9465c33fa058e2e0283576faa242a35a8129280963a7b0c908f09d3e97cd557c527e669f742c23fcd96702692280ffd4ba58fd2ff8b4d26ae26f263d6f228ef53f335fa6d33fdf513a7e6402ed02269a4d328fb1712b212420726d3e6d8996a6ebeba63c37bffcbddffabfbf91
      
      # Console
      - name: Build Console
        working-directory: newskarnataka-console
        run: npm install --legacy-peer-deps && npm run build
        env:
          VITE_STRAPI_URL: http://103.191.208.235:1337
          VITE_STRAPI_API_TOKEN: a18e5bcb9bc06d3af2e522ba790c6e9465c33fa058e2e0283576faa242a35a8129280963a7b0c908f09d3e97cd557c527e669f742c23fcd96702692280ffd4ba58fd2ff8b4d26ae26f263d6f228ef53f335fa6d33fdf513a7e6402ed02269a4d328fb1712b212420726d3e6d8996a6ebeba63c37bffcbddffabfbf91
      
      # Deploy Website
      - name: Deploy Website to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEBSITE }}
          working-directory: newskarnataka-website
      
      # Deploy Console
      - name: Deploy Console to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_CONSOLE }}
          working-directory: newskarnataka-console
