name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_Hc1spTfjdTMy2FHP8nTmuMJV
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}
    defaults:
      run:
        shell: bash
        working-directory: newskarnataka-website
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: newskarnataka-website/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Vercel CLI
        run: npm install --save-dev vercel@latest
      
      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
      
      - name: Build Project
        run: npx vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          NEXT_PUBLIC_STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_API_TOKEN_FULL_ACCESS: ${{ secrets.STRAPI_API_TOKEN }}
      
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"

  deploy-console:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_Hc1spTfjdTMy2FHP8nTmuMJV
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_CONSOLE_PROJECT_ID }}
    defaults:
      run:
        shell: bash
        working-directory: newskarnataka-console
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: newskarnataka-console/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Vercel CLI
        run: npm install --save-dev vercel@latest
      
      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
      
      - name: Build Project
        run: npx vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VITE_STRAPI_URL: ${{ secrets.STRAPI_URL }}
          VITE_STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
      
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
